### ISSUE TITLE
Nice example but could be more generic

### ISSUE THREAD

**Issue by aspcompiler** [OfficeDev/Word-Add-in-JavaScript-InvoiceManager#2]
I noticed that the 3 invoices in the example all have 6 items each. I moved some items from the 1st invoice to the 2nd. When I ran the program, the detail section does not grow or shrink according to number of items in the invoice. In the real world, we cannot expect invoices always have the same numbers of items. Can you make this example more generic?

**Comment by AndrewJByrne** [comment]
Hi aspcompiler, 

Thanks for getting in touch and I am glad you are finding our samples useful. Great suggestion also. I'll look into it and be sure to get back to you on this issue thread if I have an update. 

Thanks,
Andrew

**Comment by dcu-sharepoint** [comment]
STILL WAITING IN JANUARY OF 2017, A WHOLE TWO YEARS LATER....

are computers this S L   O     WWWWWWWWWWWWWWWWW ???????????????

**Comment by dcu-sharepoint** [comment]
WOW

**Comment by Rick-Kirkham** [comment]
I have found another sample that shows table binding with variable data: [Excel-Add-in-Bind-To-Table](https://github.com/OfficeDev/Excel-Add-in-Bind-To-Table). So, it doesn't look like there's much point to updating this sample, so I will close this issue.
