### ISSUE TITLE
PackingSlip.docx not display on online word

### ISSUE THREAD

**Issue by BhavJain** [OfficeDev/Word-Add-in-JavaScript-InvoiceManager#4]
I have uploaded menifest file and widgets render properly but not display packingslip default document its show blank document

**Comment by AndrewJByrne** [comment]
Hi BhavJain, 

Thanks for getting  in touch and sorry to hear you are having an issue.  It sounds like you are experiencing the issue listed in the Troubleshooting section of the Readme. To fix this, set the Start Document to PackingSlip.docx, as shown in this image:

![before and after property settings page](https://cloud.githubusercontent.com/assets/8550529/9298211/b29908a8-445f-11e5-8887-0b3e6a9c8649.png)

I hope that helps!

**Comment by dcu-sharepoint** [comment]
Hello Rick


I'm still trying to find information on a couple of (frustrating )things I've posted several times.


1) how to create the controls on the word document.

2) how to bind data from the javascript to the word document

3) how to make the table dynamic, in other words, say you have one row for one packing slip and 10 rows for another packing slip.

4) samples on how to get the data from an office 365 SharePoint list.


please give hints, tips of links where I can go to find this info


Thanks for you respons


________________________________

**Comment by Rick-Kirkham** [comment]
I think I've addressed these questions where you brought them up in the office-js-docs repo. At any rate, they are not really relevant to this particular issue.
