### ISSUE TITLE
Word-Add-in-JavaScript-InvoiceManager control binding and table fillin problem

### ISSUE THREAD

**Issue by dcu-sharepoint** [OfficeDev/Word-Add-in-JavaScript-InvoiceManager#6]
I'm having a problem following the OfficeDev/Word-Add-in-JavaScript-InvoiceManager found in github. can somebody please direct me to a forum or dev center office where I can ask questions.

the specific problems I'm having are: 
1) how to bind the controls in the word document to a SharePoint list. 
2) how to create a dynamic table control collections so it can be filled from list items.

these are critical as I have a customer waiting for a solution and I have not been able to find anything on the subject anywhere!

Thanks for your help

**Comment by Rick-Kirkham** [comment]
@dcu-sharepoint 
If I understand the issue that you have raised, you are, in effect, requesting a new sample that illustrates a solution your two problems. _I cannot give you a timeline_, but I will investigate whether this sample can be changed to do this without interfering with its basic purpose. Alternatively, perhaps a new sample can be developed that will help. 

Please note that creating an Issue on GitHub is mainly intended as way to report bugs in the sample. To request a new sample or significantly enhanced sample, please use [Office User Voice](https://office.uservoice.com/forums/285186-general). Here's an example: [error-code-message-documentation](https://office.uservoice.com/forums/285186-general/suggestions/9550923-error-code-message-documentation)

**Comment by Rick-Kirkham** [comment]
I have found another sample that shows table binding with variable data: [Excel-Add-in-Bind-To-Table](https://github.com/OfficeDev/Excel-Add-in-Bind-To-Table). So, it doesn't look like there's much point to updating this sample, so I will close this issue.
