### ISSUE TITLE
need help identifying the control types on the PackingSlip.docx document

### ISSUE THREAD

**Issue by dcu-sharepoint** [OfficeDev/Word-Add-in-JavaScript-InvoiceManager#7]
I need help identifying the **control types** on the **PackingSlip.docx** document included in the **example.**

Here's an image of the word document...

![tablecontrols](https://cloud.githubusercontent.com/assets/22737071/22180127/65c19a5e-e035-11e6-933e-e4b64a446ef9.png)

the controls on the **top table** are of a different color than the controls on the **table at the bottom**.
How are these controls created as **they are different** from the control created in **word 2016** and what ribbon option houses these controls. Unfortunately as you can see, the designer/properties does not show any identifying properties for these controls.

**Comment by Rick-Kirkham** [comment]
After you've added your controls to the document, save it (under a different name if you want to preserve the original). In Windows Explorer, change the file extension from docx to zip. Open the zip file. Navigate to the Word folder and open the document.xml file. This will give you the OOXML-level view of the file where you can compare the actual XML markup of the controls.

**Comment by dcu-sharepoint** [comment]
Rick


I've done that already and  don't seem to find where the controls are. I can now create a zip file from scratch in order to find the differences and I can't find them. of course, as you know there are quite a few tags and I may be missing the right tag. I've even isolated the <w:tbl> and put it a fresh document and that's where I'm currently working at.


L. Carlos Rodriguez



________________________________

**Comment by Rick-Kirkham** [comment]
You could try deleting everything except the first table and then "save as". Then do a Ctrl-Z until everything is back. Then delete everything except the 2nd table and do a "save as" under a different file name. Then compare the two document.xml files side-by-side. 

This seems to be a troubleshooting question rather than a bug in the sample, so I'm closing this.
