### ISSUE TITLE
Repeating section not updating

### ISSUE THREAD

**Issue by axl220** [OfficeDev/Word-Add-in-JavaScript-InvoiceManager#9]
Hi

This example has been a great help, but I have a bit of a bug I cant fix, the bug can easily be recreated with the invoice manager sample:

I updated the xml so the first order only has one item, the second order have two items.

When you select the first order and populate it, it populates the repeating section with the one item but if you search the second order and click populate only the first item displays. You can click on the little plus on the table row and it will create a new row with the missing value. I would like to do this programmatcaly.

If you change this and add five items to the first order and only one in the second order, when you now select the second order after populating the first, it will display the second orders items and the first orders items.

Do you know how to refresh / update the repeating section? 

Or do you have a fix for this?

Regards,
Dieter

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained.
